### ISSUE TITLE
incompatible storage from cabal-cli / multicabal

### ISSUE THREAD

**Issue by telamon** [cabal-club/cabal-irc#5]
I've noticed that the multi-cabal patch provided some nice improvements to the 
local storage on a users device. And a new set of flags:
 https://github.com/cabal-club/cabal/commit/cf322c0da809320df1170f97cba656215712af2b

I tried patching cabal-irc previously to follow the same cli.js scheme but after a closer inspection and testing i realize that cabal-irc is lacking a lot more than i initially expected.

I think just replicating the logic and cabal.yml handling in `cabal-irc` would just invite an unmaintainable situation. Instead I'd like to propose to incorporate the multi-cabal functionality and storage-structure into `cabal-core` or a separate module that can be shared between all implementing clients in order to let users reuse their original cabal-identities across clients.

**Comment by hackergrrl** [comment]
I *think* this is no longer necessary, since cabal-client now handles multiple cabals. Thanks @telamon!
